[config]

# the user you want to mimic
user = "dan" 

user_id = "U03MJE91EET"

# relative or absolute path to the slack export
history_path = "../goofyspot_history/" 

# where to save the JSONL file
output_path = "../goofyspot_history/dan_history.jsonl"

# the channels to include, leave empty to get all channels or delete
channels = ["general"] 

# the number of previous chats to use when building the prompt
num_prev_msgs = 5

# whether or not to include the channel as context at the beginning of the prompt
inc_channel_name = true

# the token used to end the completion
endtoken = "<e>"

# the token used to denote no previous message was seen
noprevtoken = "<n>"

# the fine tuned model
#default_engine = "ada:ft-personal-2022-07-01-06-39-13"
#default_engine = "curie:ft-personal-2022-07-01-22-09-51"
default_engine = "ft:gpt-3.5-turbo-0613:personal::7rKY9jda"

# the suffix used in a prompt to end it
prompt_suffix = "\n\n###\n\n"

# the baseline temp of the completion
temperature = 0.70

# the maximum number of tokens per request
max_tokens = 75

# the max number of replies allowed for a given thread
max_thread_replies = 1000
